### ISSUE TITLE
JMX Management API for JBoss lacks of an operation to enumerate SIP Connectors

### ISSUE THREAD

**Issue by ocarriles** [RestComm/sip-servlets#198]
As I can see, adding/removing is possible but list/find is not available.
It would be possible to add an operation like "findSipConnectors" implemented yet in Tomcat flavor?

**Comment by jaimecasero** [comment]
![image](https://user-images.githubusercontent.com/7847241/26871483-98994752-4b73-11e7-8224-9454d7f0b497.png)
this is how connectors looks like in jconsole

**Comment by jaimecasero** [comment]
![image](https://user-images.githubusercontent.com/7847241/26871564-f2b4c022-4b73-11e7-8be3-f4daf328e9a4.png)
same for tomcat

**Comment by jaimecasero** [comment]
@ocarriles as you can see the connectors are listed as JMX Mbeans themselves, and not as an operation. This is in my opinion very convenient, since then you dont need to depend on some particular nonJMX interface, and you get a full object in the JMX directory. I think the naming convention fot those objects is predictable enough to find them as expected in [JMX best practices](http://www.oracle.com/technetwork/java/javase/tech/best-practices-jsp-136021.html?ssSourceSiteId=ocomen#mozTocId654884).

If you are wondering how to programatically find those MBeans using no naming convention, i think you need to use the JMX query engine using the type of object, in this case "SipConnector" as explained here https://stackoverflow.com/questions/34508184/jmx-mbeanserver-querymbeans-with-query-exp-does-not-work

so i think this query would work for you
`
String objectName = "*:type=SipConnector";
Set<ObjectInstance> instances = server.queryMBeans(new ObjectName(objectName), null);
`

**Comment by ocarriles** [comment]
thanks @jaimecasero  for your detailed explanation.
let me try and be back to ACK results.
