### ISSUE TITLE
Broken maven dependencies

### ISSUE THREAD

**Issue by gsaslis** [RestComm/sip-servlets#349]
Running `mvn clean compile war:war` on a clean checkout from master, results in dependency not found. 

Version `1.3.0-25` of `jain-sip-ri` does not exist in https://oss.sonatype.org/content/groups/public/javax/sip/jain-sip-ri/ .

**Comment by jaimecasero** [comment]
Seems to be caused by the fact we have changed CI envinroment and the artifact repository (nexus...). Probably we need to include the new repository as part of declared repositories in project pom. bad news again is that CXS repo is not opened to public access, and credentials will be required anyway. You need a settings.xml file in your maven installation to provide the CXS repo and the credentials.

**Comment by deruelle** [comment]
@jaimecasero the new CI env should have an option to push a release to sonatype and once it's published the community version should use that. Let's make sure we push the version to sonatype from CI itself.
