### ISSUE TITLE
Gather basic usage stats 

### ISSUE THREAD

**Issue by ivelin** [RestComm/sip-servlets#60]
Many users and prospects ask what is the scale of use of Mobicents products. We should add a simple counter in the server to report completed call minutes and delivered messages, along with public IP of the server. The aggregated stats from around the world can be reported live back to the community.

<a href="https://timer.scm.io/repos/568d57c1960600c479a206a7/issues/60/create?referer=github" target="_blank">Log Time</a>

**Comment by jaimecasero** [comment]
I'll have a look where to place the counters, and how to query them (MBean). Lets clarify this is not an statistical measurement facility, collected in time intervals, this is more server-side counters, so much alike netstat -s feature by Linux, where you need to reset the machine to start the counters again. It is important to close the scope of this features, since collecting stats may impact performance.

By the way,  i suggests to use AppRouter, since is the central place where all SIP messages passes.

Completed call minutes may be specially heavy in performance, i will see to implement in a lightweight fashion.

**Comment by jaimecasero** [comment]
SipApplicationDispatcher seems another good candidate to place this counter logic

**Comment by deruelle** [comment]
Hi Jaime,

AppRouter is not a good place as it sees only initial requests not subsequent requests so there will be no way to compute the number of minutes.

On Statistics we already have some in SipApplicationDispatcher, look for gatherStatistics in this file https://github.com/Mobicents/sip-servlets/blob/master/sip-servlets-impl/src/main/java/org/mobicents/servlet/sip/core/SipApplicationDispatcherImpl.java. 

It records all requests and responses received and sent

There is also statistics recorded per application https://github.com/Mobicents/sip-servlets/blob/master/sip-servlets-core-api/src/main/java/org/mobicents/servlet/sip/core/SipManager.java

**Comment by deruelle** [comment]
The scope is really to record number of messages (requests, responses received and sent - we already have those ones) and number of minutes (we don't have those) and send those metrics (at regular intervals) to a central server (this part will need to be created too) so we can display the stats to the community

**Comment by jaimecasero** [comment]
Ok Jean, then I understood the other way aroud. Now is more clear to me.
